env:
  global:
    CODECOV_TOKEN:
      secure: vy/3wPcF7ktiSPdEGmhsgJS109HF78jPJbJAscK/v+qaMX+U329B0XENdkwSMQwRTep4LPSvaKo33wfUHqGgCLk3dxlXQe4ZFQ9PxPK1/fZCuZqeZjdziGfR9qn76WncGZglcuo2jRl6ILpfAqMN5UyeFE3b7y+hFIf5TbOhfOiuD0IxGLeWup3Ygzbp9RScEKSgoacnCP9+/xfXDKLeWGODIuc0kDgpCspTerfnttHP8Td9+J7cWgtiTSZa8m6eGDgPl2teLy5/GfBmWeeC+MXw0S94cSSBqZEJdoYCNgN/L3qPZBozjOUIN7g91PjOqORAEtLKjVhh6e4kxll+CcYlQ4f8nwd4qvLtYreLjHsu1mW/G4cJwFvZrYgNSr9K/Mx/Iv2zNKe8G9Rvyewk3rnlaZRQzEmLFGGyzXeTkNe+yjNDwD+JnVb4nIJdq1lMQWPnF6mnw9leQLw9BOBWXlQH4HBZeuEkn6G94IZNzQIHnnx2/jBsJBX800JS6eQEoDw1mMnSBLuOcvTepcFSmNZtxhAgtL36tA5Qs+BWWCZ24vNwM8QIdAOUUlVVTMCIGNlMpD34WphyAM+RHhFbZzPVRJvDDQckrXpMyiCfeN21SwjsG/JMCfprncRd3QCx3wp6vukO+n9insDjsS61if+pcFa8r+y7GWfwpd8F43g=

language: python

matrix:

  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.7
      env: TOXENV=py37

install:
  - pip install tox

script:
  - tox

deploy:
  provider: pypi
  user: arno49
  password:
    secure: PRelwjuuhHe4Kn449uBpfUBdu8Ppj6OafFlfPxSpTlipWAiRkRCy6W9mNaN/ivf1kv+Hk1RRv/ZLCZVqH0KrPDN8ovGcBsqVOP66PfRaqy7k68X4W2wNJaQtLwIEwqj37GUfW8G43qiDKfrTtRiY1cRfN7LbqogbrEXYITYtCwcaxhogKgVH8DQlirjy4danDJeNT02GuU0RfXztxPXLM1GkbvPLsvjFJNkCJTUJl4Hi1YDzN7J9LJzfsm751k7Pt9qXG/z9e+MLB7J0hhsnMV3ihTtwRaoBdea7z6d3LTl9INqIdkB4Wcg8T5A+NESRvEIZFrn6jToiNe9tPkGJCL80hjMXKBLnhVt42AJ2NG5Z1ilUHJkivR84FbFRTc5oZKe8X6SjhEXF5JHb4BNBuAPptZ6t9ex3t6opay2lxrzroCkPlvykLm9Tao7x/JLwCL+p671Ka8w/xJvWD6aGYvKPDKmNVQBsmtrEKpO0n2bx8gH7Fjii+DXwNEzekx5rLVUgJlQNBXo9IBkHFyfZX2HpzV8PRuTIgrSxrvmUfVVJFhUjpymbbc2kUuZyPGj82bDtzsidkgKRbWZsg6NXDpcBnKE26xh/WqF0REO69xd5b/tO53oRwq1ZmooX4H7hWAW5rGu71MUAjaGR1SU3+uxwx30nhnYbEYbJKVXKNCw=
  distributions: sdist bdist_wheel --universal
  on:
    tags: true
